// Use enhanced store with proper persistence - export through store.ts for consistency
export { store, type RootState, type AppDispatch, initializeStoreData } from './store';
export { initializeSQLitePersistence } from './middleware/simplifiedPersistenceMiddleware';
export * from './slices/tasksSlice';
export * from './slices/projectsSlice';
export * from './slices/journalSlice';
export * from './slices/userSlice';
export * from './slices/uiSlice';
export * from './slices/tagsSlice';
export * from './slices/authSlice';
export * from './slices/databaseSlice';
export { initializeDatabaseConfig } from './slices/databaseSlice';
export * from './slices/shortcutsSlice';
export * from './slices/searchSlice';
export * from './slices/dragDropSlice';
export * from './slices/integrationsSlice';
export { initializeIntegrations } from './slices/integrationsSlice';
export * from './slices/aiAssistantSlice';
export * from './slices/goalsSlice';
export * from './slices/sampleData';